<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CompanyList.aspx.cs" Inherits="OffCampusHousing.CompanyList" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <style>
        body{
            background-image:url("http://www.rmschicago.com/wp-content/themes/rmschicago/images/background-photo.jpg");
        }
    </style>
 
</head>
<body >
    <form id="form1" runat="server">
        <font color="#007acc">
            <h1>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                Company List
            </h1>
        </font>
    <div>
    <table align="center">
        <tr>
            
        <td>
    
        <asp:GridView ID="gvCompany" runat="server" CellPadding="4" ForeColor="Black" GridLines="Horizontal" AllowSorting="True" OnRowEditing="gvCompany_RowEditing" DataKeyNames="Id" 
            AutoGenerateEditButton="True" OnRowDeleting="gvCompany_RowDeleting" AutoGenerateDeleteButton="True" Height="226px" Width="674px" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" >
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#242121" />
        </asp:GridView>
        <table>
            <tr>
                <td><asp:Button ID="btnAdd" Text="Add" runat="server" OnClick="btnAdd_Click" Width="92px" /></td>
                
            </tr>
           
        </table>
             </td>
            </tr>
        </table>
        </div>
    </form>
</body>
</html>
