//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OffCampusHousing
{
    using System;
    using System.Collections.Generic;
    
    public partial class gmap
    {
        public int Id { get; set; }
        public string Area { get; set; }
        public string Name { get; set; }
        public string LocLat { get; set; }
        public string LocLong { get; set; }
        public string ReadUrl { get; set; }
        public string Type { get; set; }
    }
}
