<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UserList.aspx.cs" Inherits="OffCampusHousing.UserList" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            text-align: center;
            text-decoration: underline;
        }
        body{
            background-image:url("https://santaguidafinefoods.com/file/2014/08/web-design-fp-home-page-background.jpg");
        }
        .newStyle1 {
            color: #990000;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <h1 class="auto-style1"><em class="newStyle1">Users List for Star Properties</em></h1>
        <br />
    <table align="Center">
        <tr>
        <td colspan="2">
        <asp:GridView ID="gvUser" runat="server" OnRowEditing="gvUser_RowEditing" OnRowDeleting="gvUser_RowDeleting" 
            AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" DataKeyNames="Id" AllowSorting="True" CellPadding="4" ForeColor="#333333" GridLines="None" Height="379px" Width="831px"   >
            <AlternatingRowStyle BackColor="White" />
            <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
            <SortedAscendingCellStyle BackColor="#FDF5AC" />
            <SortedAscendingHeaderStyle BackColor="#4D0000" />
            <SortedDescendingCellStyle BackColor="#FCF6C0" />
            <SortedDescendingHeaderStyle BackColor="#820000" />

        </asp:GridView>
            </td>
            </tr>
        <tr>
            <td>
                <asp:Button ID="btnAdd" runat="server" Text="LoginPage" OnClick="btnAdd_Click" Width="74px" />
            </td>
            <td>
                <asp:Button ID="btnAdmin" runat="server" Text="AdminPage" Width="94px" OnClick="btnAdmin_Click" />
            </td>
        </tr>
    </table>
    </div>
    </form>
</body>
</html>
